In [1]:
import pandas as pd

In [2]:
pd.read_csv("f.csv")

,tuple,count,G_test,G_sigmoid,G_relu_sum,G_relu_prod,G_relu_prod_1000
0,"(0, 0, 0, 0)",0,0.917585,0.500000,0.00,1.0,1.000000e+00
1,"(0.01, 0.01, 0.01, 0.01)",0,0.536847,0.268941,0.00,1.0,-9.998999e+03
2,"(-0.01, -0.01, -0.01, -0.01)",4,0.982023,0.731059,0.04,1.0,1.000000e+00
3,"(-0.01, -0.01, -0.01, -0.01, 1)",4,0.982023,0.731059,0.04,1.0,1.000000e+00
4,"(0.01, 0.01, 0.01, 0.01, -1)",1,0.831094,1.000000,1.00,1.0,1.000000e+00
5,"(0.01, 0.01, 0.01, 0.01, 1)",0,0.536847,0.268941,0.00,1.0,-9.999998e+06
6,"(-0.5, -0.5, -0.5, -0.5)",4,0.982026,1.000000,2.00,1.0,1.000000e+00

G_relu_prod may look like it's always outputting the same thing, but it's just very close to 1. It behaves like G_relu_prod_1000

Initialize next to Peterson configuration, use scipy's gradienct descent (BFGS, actively uses line search for optimum step size)

In [4]:
df = pd.read_csv("t1_scipy.csv")
df

,G,iterations,optimized val,edges cut by config,optimize func of t1,regularization,filename,intersections,performance
0,G_test,0,-1.645856e+02,192,-164.585552,NaN,t1_scipy,"(52, 60, 60, 52, 48)",1.000000
1,G_test,2,-1.794589e+02,122,-164.585552,ridge,t1_scipy,"(32, 48, 56, 32, 32)",0.635417
2,G_test,10,-1.629069e+02,178,-164.585552,bound_sigmoid,t1_scipy,"(60, 60, 60, 60, 60)",0.927083
3,G_test,0,-1.446039e+02,110,-164.585552,bound_softmax,t1_scipy,"(60, 60, 60, 60, 60)",0.572917
4,G_sigmoid,0,-1.920000e+02,192,-192.000000,NaN,t1_scipy,"(52, 60, 60, 52, 48)",1.000000
5,G_sigmoid,2,-9.600000e+01,130,-192.000000,ridge,t1_scipy,"(32, 60, 56, 32, 32)",0.677083
6,G_sigmoid,143,-1.819873e+02,182,-192.000000,bound_sigmoid,t1_scipy,"(60, 60, 60, 60, 60)",0.947917
7,G_sigmoid,0,-1.100000e+02,110,-192.000000,bound_softmax,t1_scipy,"(60, 60, 60, 60, 60)",0.572917
8,G_relu_sum,1,-2.682906e+07,136,-3232.000000,NaN,t1_scipy,"(60, 60, 52, 32, 32)",0.708333
9,G_relu_sum,1,-2.577578e+07,134,-3232.000000,ridge,t1_scipy,"(60, 60, 52, 32, 32)",0.697917
10,G_relu_sum,51,-4.609091e+01,174,-3232.000000,bound_sigmoid,t1_scipy,"(60, 60, 60, 60, 60)",0.906250
11,G_relu_sum,19,-7.499999e+01,110,-3232.000000,bound_softmax,t1_scipy,"(60, 60, 60, 60, 60)",0.572917
12,G_relu_prod,0,-1.920000e+02,192,-192.000000,NaN,t1_scipy,"(52, 60, 60, 52, 48)",1.000000
13,G_relu_prod,2,-1.920000e+02,122,-192.000000,ridge,t1_scipy,"(32, 48, 56, 32, 32)",0.635417
14,G_relu_prod,1,-1.917901e+02,180,-192.000000,bound_sigmoid,t1_scipy,"(48, 60, 60, 60, 60)",0.937500
15,G_relu_prod,28,1.778503e+05,110,-192.000000,bound_softmax,t1_scipy,"(60, 60, 60, 60, 60)",0.572917
16,G_relu_prod_1000,0,-1.920000e+02,192,-192.000000,NaN,t1_scipy,"(52, 60, 60, 52, 48)",1.000000
17,G_relu_prod_1000,2,-1.920000e+02,122,-192.000000,ridge,t1_scipy,"(32, 48, 56, 32, 32)",0.635417
18,G_relu_prod_1000,1,2.099359e+14,180,-192.000000,bound_sigmoid,t1_scipy,"(48, 60, 60, 60, 60)",0.937500
19,G_relu_prod_1000,4,1.764480e+20,84,-192.000000,bound_softmax,t1_scipy,"(60, 60, 60, 48, 60)",0.437500

G function/regularization combinations that did not stray

In [10]:
df[df.loc[:,df.columns[3]]==192][["G","regularization"]]

                   G regularization
0             G_test            NaN
4          G_sigmoid            NaN
12       G_relu_prod            NaN
16  G_relu_prod_1000            NaN

Initialize next to Peterson configuration, use Adam optimizer from Torch

In [13]:
df = pd.read_csv("t1_adam.csv")
df

,G,iterations,optimized val,edges cut by config,optimize func of t1,regularization,filename,intersections,performance
0,G_test,60,-1.645856e+02,192,-164.585552,NaN,t1_adam,"(52, 60, 60, 52, 48)",1.000000
1,G_test,60,-1.311483e+02,132,-164.585552,ridge,t1_adam,"(42, 44, 60, 32, 32)",0.687500
2,G_test,60,-1.637036e+02,156,-164.585552,bound_sigmoid,t1_adam,"(52, 56, 60, 52, 48)",0.812500
3,G_test,60,-1.446039e+02,192,-164.585552,bound_softmax,t1_adam,"(52, 60, 60, 52, 48)",1.000000
4,G_sigmoid,60,-1.920000e+02,192,-192.000000,NaN,t1_adam,"(52, 60, 60, 52, 48)",1.000000
5,G_sigmoid,60,-6.569991e+01,167,-192.000000,ridge,t1_adam,"(52, 54, 48, 52, 48)",0.869792
6,G_sigmoid,60,-1.819630e+02,150,-192.000000,bound_sigmoid,t1_adam,"(56, 56, 60, 56, 32)",0.781250
7,G_sigmoid,60,NaN,0,-192.000000,bound_softmax,t1_adam,"(0, 0, 0, 0, 0)",0.000000
8,G_relu_sum,60,-2.113784e+04,182,-3232.000000,NaN,t1_adam,"(48, 60, 60, 52, 48)",0.947917
9,G_relu_sum,60,-1.942896e+04,182,-3232.000000,ridge,t1_adam,"(48, 60, 60, 52, 48)",0.947917
10,G_relu_sum,60,-4.573414e+01,128,-3232.000000,bound_sigmoid,t1_adam,"(48, 60, 40, 52, 32)",0.666667
11,G_relu_sum,60,-7.493333e+01,123,-3232.000000,bound_softmax,t1_adam,"(36, 54, 36, 54, 32)",0.640625
12,G_relu_prod,60,-1.920000e+02,192,-192.000000,NaN,t1_adam,"(52, 60, 60, 52, 48)",1.000000
13,G_relu_prod,60,-3.788770e+00,192,-192.000000,ridge,t1_adam,"(52, 60, 60, 52, 48)",1.000000
14,G_relu_prod,60,-1.919962e+02,117,-192.000000,bound_sigmoid,t1_adam,"(48, 58, 60, 32, 40)",0.609375
15,G_relu_prod,60,1.735961e+05,130,-192.000000,bound_softmax,t1_adam,"(32, 48, 32, 60, 60)",0.677083
16,G_relu_prod_1000,60,-1.920000e+02,192,-192.000000,NaN,t1_adam,"(52, 60, 60, 52, 48)",1.000000
17,G_relu_prod_1000,60,1.668783e+19,174,-192.000000,ridge,t1_adam,"(52, 60, 60, 52, 48)",0.906250
18,G_relu_prod_1000,60,4.040814e+12,117,-192.000000,bound_sigmoid,t1_adam,"(48, 58, 60, 32, 40)",0.609375
19,G_relu_prod_1000,60,1.737881e+20,130,-192.000000,bound_softmax,t1_adam,"(32, 48, 32, 60, 60)",0.677083

G function/regularization combinations that did not stray

In [12]:
df[df.loc[:,df.columns[3]]==192][["G","regularization"]]

                   G regularization
0             G_test            NaN
3             G_test  bound_softmax
4          G_sigmoid            NaN
12       G_relu_prod            NaN
13       G_relu_prod          ridge
16  G_relu_prod_1000            NaN

Adam optimizer, initilized as all ones

In [16]:
df = pd.read_csv("h_adam_low.csv")
df[df.d==6]

,"(k,d)",d,G,reg,count,filename,intersections,performance
60,"(5, 6)",6,G_test,NaN,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
61,"(5, 6)",6,G_test,ridge,30,h_adam_low,"(30, 30, 30, 30, 30)",0.15625
62,"(5, 6)",6,G_test,bound_sigmoid,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
63,"(5, 6)",6,G_test,bound_softmax,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
64,"(5, 6)",6,G_sigmoid,NaN,60,h_adam_low,"(0, 60, 60, 60, 60)",0.31250
65,"(5, 6)",6,G_sigmoid,ridge,60,h_adam_low,"(0, 60, 60, 60, 60)",0.31250
66,"(5, 6)",6,G_sigmoid,bound_sigmoid,126,h_adam_low,"(60, 6, 60, 60, 60)",0.65625
67,"(5, 6)",6,G_sigmoid,bound_softmax,0,h_adam_low,"(0, 0, 0, 0, 0)",0.00000
68,"(5, 6)",6,G_relu_sum,NaN,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
69,"(5, 6)",6,G_relu_sum,ridge,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
70,"(5, 6)",6,G_relu_sum,bound_sigmoid,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
71,"(5, 6)",6,G_relu_sum,bound_softmax,0,h_adam_low,"(0, 0, 0, 0, 0)",0.00000
72,"(5, 6)",6,G_relu_prod,NaN,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
73,"(5, 6)",6,G_relu_prod,ridge,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
74,"(5, 6)",6,G_relu_prod,bound_sigmoid,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
75,"(5, 6)",6,G_relu_prod,bound_softmax,30,h_adam_low,"(30, 30, 30, 30, 30)",0.15625
76,"(5, 6)",6,G_relu_prod_1000,NaN,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
77,"(5, 6)",6,G_relu_prod_1000,ridge,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
78,"(5, 6)",6,G_relu_prod_1000,bound_sigmoid,60,h_adam_low,"(60, 60, 60, 60, 60)",0.31250
79,"(5, 6)",6,G_relu_prod_1000,bound_softmax,30,h_adam_low,"(30, 30, 30, 30, 30)",0.15625

Adam optimizer, initilized with random 10-range

In [17]:
df = pd.read_csv("h_adam.csv")
df[df.d==6]

,"(k,d)",d,G,reg,count,filename,intersections,performance
60,"(5, 6)",6,G_test,NaN,153,h_adam,"(48, 46, 56, 40, 52)",0.796875
61,"(5, 6)",6,G_test,ridge,160,h_adam,"(60, 58, 50, 60, 50)",0.833333
62,"(5, 6)",6,G_test,bound_sigmoid,158,h_adam,"(50, 56, 60, 58, 56)",0.822917
63,"(5, 6)",6,G_test,bound_softmax,150,h_adam,"(60, 48, 56, 48, 54)",0.781250
64,"(5, 6)",6,G_sigmoid,NaN,54,h_adam,"(0, 54, 0, 0, 0)",0.281250
65,"(5, 6)",6,G_sigmoid,ridge,44,h_adam,"(0, 0, 44, 0, 0)",0.229167
66,"(5, 6)",6,G_sigmoid,bound_sigmoid,153,h_adam,"(54, 56, 56, 46, 60)",0.796875
67,"(5, 6)",6,G_sigmoid,bound_softmax,0,h_adam,"(0, 0, 0, 0, 0)",0.000000
68,"(5, 6)",6,G_relu_sum,NaN,155,h_adam,"(60, 48, 48, 52, 60)",0.807292
69,"(5, 6)",6,G_relu_sum,ridge,155,h_adam,"(48, 50, 58, 54, 60)",0.807292
70,"(5, 6)",6,G_relu_sum,bound_sigmoid,154,h_adam,"(60, 48, 48, 48, 58)",0.802083
71,"(5, 6)",6,G_relu_sum,bound_softmax,116,h_adam,"(60, 60, 42, 28, 60)",0.604167
72,"(5, 6)",6,G_relu_prod,NaN,155,h_adam,"(54, 40, 50, 46, 54)",0.807292
73,"(5, 6)",6,G_relu_prod,ridge,143,h_adam,"(36, 60, 44, 50, 46)",0.744792
74,"(5, 6)",6,G_relu_prod,bound_sigmoid,150,h_adam,"(36, 60, 54, 56, 48)",0.781250
75,"(5, 6)",6,G_relu_prod,bound_softmax,143,h_adam,"(48, 20, 48, 50, 58)",0.744792
76,"(5, 6)",6,G_relu_prod_1000,NaN,154,h_adam,"(50, 24, 58, 52, 60)",0.802083
77,"(5, 6)",6,G_relu_prod_1000,ridge,149,h_adam,"(32, 58, 40, 58, 54)",0.776042
78,"(5, 6)",6,G_relu_prod_1000,bound_sigmoid,155,h_adam,"(50, 46, 52, 36, 58)",0.807292
79,"(5, 6)",6,G_relu_prod_1000,bound_softmax,140,h_adam,"(40, 54, 48, 52, 56)",0.729167

scipy optimizer, initilized as all ones

In [18]:
df = pd.read_csv("h_scipy.csv")
df[df.d==6]

,"(k,d)",d,G,reg,count,filename,intersections,performance
60,"(5, 6)",6,G_test,NaN,159,h_scipy,"(52, 58, 48, 48, 54)",0.828125
61,"(5, 6)",6,G_test,ridge,155,h_scipy,"(60, 50, 60, 40, 56)",0.807292
62,"(5, 6)",6,G_test,bound_sigmoid,173,h_scipy,"(60, 56, 60, 60, 60)",0.901042
63,"(5, 6)",6,G_test,bound_softmax,60,h_scipy,"(60, 60, 60, 60, 60)",0.312500
64,"(5, 6)",6,G_sigmoid,NaN,154,h_scipy,"(56, 52, 52, 60, 38)",0.802083
65,"(5, 6)",6,G_sigmoid,ridge,150,h_scipy,"(52, 40, 38, 60, 54)",0.781250
66,"(5, 6)",6,G_sigmoid,bound_sigmoid,178,h_scipy,"(54, 60, 60, 60, 60)",0.927083
67,"(5, 6)",6,G_sigmoid,bound_softmax,60,h_scipy,"(60, 60, 60, 60, 60)",0.312500
68,"(5, 6)",6,G_relu_sum,NaN,151,h_scipy,"(48, 58, 48, 60, 52)",0.786458
69,"(5, 6)",6,G_relu_sum,ridge,151,h_scipy,"(44, 52, 38, 60, 32)",0.786458
70,"(5, 6)",6,G_relu_sum,bound_sigmoid,164,h_scipy,"(60, 60, 60, 48, 60)",0.854167
71,"(5, 6)",6,G_relu_sum,bound_softmax,60,h_scipy,"(60, 60, 60, 60, 60)",0.312500
72,"(5, 6)",6,G_relu_prod,NaN,156,h_scipy,"(50, 52, 48, 58, 54)",0.812500
73,"(5, 6)",6,G_relu_prod,ridge,154,h_scipy,"(52, 46, 54, 52, 44)",0.802083
74,"(5, 6)",6,G_relu_prod,bound_sigmoid,162,h_scipy,"(38, 58, 48, 54, 60)",0.843750
75,"(5, 6)",6,G_relu_prod,bound_softmax,120,h_scipy,"(60, 60, 60, 60, 60)",0.625000
76,"(5, 6)",6,G_relu_prod_1000,NaN,157,h_scipy,"(50, 60, 30, 42, 54)",0.817708
77,"(5, 6)",6,G_relu_prod_1000,ridge,144,h_scipy,"(52, 52, 46, 44, 52)",0.750000
78,"(5, 6)",6,G_relu_prod_1000,bound_sigmoid,160,h_scipy,"(48, 48, 60, 60, 50)",0.833333
79,"(5, 6)",6,G_relu_prod_1000,bound_softmax,120,h_scipy,"(60, 60, 60, 60, 60)",0.625000